name: Deploy to Staging

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  deployments: write

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the jozo Admin app
        run: npm run build

      - name: Get commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/jozo-admin:${{ env.sha_short }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jozo-admin:${{ env.sha_short }}

      - name: Get commit SHA
        id: get-sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create commit SHA file
        run: echo "${{ env.sha_short }}" > commit-sha.txt

      - name: Upload commit SHA as artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: commit-sha
          path: ./commit-sha.txt

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:
      - name: Download commit SHA artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: commit-sha

      - name: Read commit SHA
        id: vars
        run: echo "sha=$(cat commit-sha.txt)" >> $GITHUB_ENV

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            docker stop jozo-admin || true
            docker rm jozo-admin || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/jozo-admin:${{ env.sha }}
            docker run -d --name jozo-admin -p 3001:3001 ${{ secrets.DOCKER_USERNAME }}/jozo-admin:${{ env.sha }}

      - name: Run deployment action in Jira
        uses: chrnorm/deployment-action@releases/v1
        with:
          environment: "staging"
          token: ${{ secrets.GITHUB_TOKEN }}
          description: "Deploying jozo-admin to staging via Docker"

  cleanup:
    runs-on: ubuntu-latest
    if: always() # Run this job even if the build fails

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove old Docker images from VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            docker image prune -f --filter "until=24h"

      - name: Remove old images from Docker Hub
        run: |
          images=$(docker images -q --filter "dangling=true")
          if [ -n "$images" ]; then
            docker rmi $images
          fi
